apiVersion: skaffold/v2beta16
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infrastructure/k8s/*
build:
  # local:
  #   push: false
  googleCloudBuild:
    projectId: ticketing-dev-312523
  artifacts:
    - image: us.gcr.io/ticketing-dev-312523/auth
      buildpacks:
        builder: gcr.io/buildpacks/builder:v1
      context: auth
      # docker:
      #   dockerfile: Dockerfile
      # sync:
      #   auto: true

      # manual:
      #   - src: "src/**/*.ts"
      #     dest: .
