apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-srv
  annotations:
    ingressclass.kubernetes.io/nginx: "true"
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - host: tickets.dev
      http: 
        paths:
          - pathType: "Prefix"
            path: /api/users
            backend:
              service:
                name: auth-service 
                port: 
                  number: 3000  